// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHlerwJe9d5FnORoE8jEzLgMtsSQ2baR8',
    appId: '1:399766360330:web:5d844a8ed2506a84822af3',
    messagingSenderId: '399766360330',
    projectId: 'sports-pwa69',
    authDomain: 'sports-pwa69.firebaseapp.com',
    storageBucket: 'sports-pwa69.firebasestorage.app',
    measurementId: 'G-GECWHR4GRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6-BLf4aIO_twASNdWvFyWDPrwiC_wVE',
    appId: '1:399766360330:android:eab85ae78b99a0a1822af3',
    messagingSenderId: '399766360330',
    projectId: 'sports-pwa69',
    storageBucket: 'sports-pwa69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB93ZmBvMUAVvUxwnZytB_0hCLzKplAbyo',
    appId: '1:399766360330:ios:a8d8a61210ad9c9b822af3',
    messagingSenderId: '399766360330',
    projectId: 'sports-pwa69',
    storageBucket: 'sports-pwa69.firebasestorage.app',
    iosClientId: '399766360330-41d7ouaig3ohmclsuvu44ommepd7ojoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB93ZmBvMUAVvUxwnZytB_0hCLzKplAbyo',
    appId: '1:399766360330:ios:a8d8a61210ad9c9b822af3',
    messagingSenderId: '399766360330',
    projectId: 'sports-pwa69',
    storageBucket: 'sports-pwa69.firebasestorage.app',
    iosClientId: '399766360330-41d7ouaig3ohmclsuvu44ommepd7ojoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHlerwJe9d5FnORoE8jEzLgMtsSQ2baR8',
    appId: '1:399766360330:web:5eef12cde2e373f1822af3',
    messagingSenderId: '399766360330',
    projectId: 'sports-pwa69',
    authDomain: 'sports-pwa69.firebaseapp.com',
    storageBucket: 'sports-pwa69.firebasestorage.app',
    measurementId: 'G-PMCN1Q5KSF',
  );
}
